In [46]:
import pandas as pd

In [47]:
# reading the csv file
df_exams = pd.read_csv('student_performance.csv')
df_exams.head()

,Student_ID,Gender,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result
0,1,Male,21,14,93,93,1,71,74,Pass
1,2,Female,21,21,94,69,1,95,79,Pass
2,3,Male,17,24,83,73,8,50,53,Pass
3,4,Male,19,28,52,99,4,59,74,Fail
4,5,Male,18,9,86,98,1,63,87,Pass


## 1 Adding a new column

### 1.1 adding a new column with a scalar value

In [48]:
# adding a new column to database
df_exams['Language_Score'] = 70
df_exams

,Student_ID,Gender,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result,Language_Score
0,1,Male,21,14,93,93,1,71,74,Pass,70
1,2,Female,21,21,94,69,1,95,79,Pass,70
2,3,Male,17,24,83,73,8,50,53,Pass,70
3,4,Male,19,28,52,99,4,59,74,Fail,70
4,5,Male,18,9,86,98,1,63,87,Pass,70
...,...,...,...,...,...,...,...,...,...,...,...
495,496,Male,21,21,73,83,0,40,77,Pass,70
496,497,Male,21,18,69,63,10,96,55,Pass,70
497,498,Female,20,35,86,85,6,68,41,Fail,70
498,499,Male,18,28,53,82,5,84,79,Fail,70


### 1.2 Adding new column using Array


In [49]:
# create an array with elements same as the number of rows in dataframe
import numpy as np

In [50]:
# create Array of 500 rows using .arange(start, stop, increment)
l_score = np.arange(0,500,1)
l_score

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [51]:
# length of the Array
len(l_score)

500

In [52]:
# adding new column to dataframe using an array
df_exams['Language_score'] = l_score
df_exams

,Student_ID,Gender,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result,Language_Score,Language_score
0,1,Male,21,14,93,93,1,71,74,Pass,70,0
1,2,Female,21,21,94,69,1,95,79,Pass,70,1
2,3,Male,17,24,83,73,8,50,53,Pass,70,2
3,4,Male,19,28,52,99,4,59,74,Fail,70,3
4,5,Male,18,9,86,98,1,63,87,Pass,70,4
...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,Male,21,21,73,83,0,40,77,Pass,70,495
496,497,Male,21,18,69,63,10,96,55,Pass,70,496
497,498,Female,20,35,86,85,6,68,41,Fail,70,497
498,499,Male,18,28,53,82,5,84,79,Fail,70,498


In [53]:
# create random integer numbers between 1 to 100
int_dialect_score = np.random.randint(1,100,size=500)
int_dialect_score

array([51, 91, 86, 49, 65, 48, 88, 48, 15, 44,  6, 43, 25, 57, 45, 36, 33,
       45, 34, 41, 72, 21, 31, 93, 52, 10, 23,  7, 89, 28, 88, 81,  5, 60,
       68, 97, 98, 13, 45, 39, 56, 69, 73, 79, 32, 94, 87, 25, 21, 26, 32,
       51, 66, 37, 22, 61, 51, 25, 49, 69, 58, 73, 24, 32, 31, 33,  6, 72,
       96, 67, 44, 89, 83,  8, 72, 48, 51, 97, 37, 30, 18, 97, 14, 82, 42,
       68, 35, 20, 76, 81,  1, 69, 74,  1, 90, 41,  9, 70, 13, 33, 31,  4,
       35, 40, 25,  4, 49, 88, 87, 71,  9,  2, 55, 35,  3, 94, 32, 16, 21,
       48, 93, 22, 92, 46,  5, 24, 85, 34, 26, 39,  7, 98, 76, 16, 48, 67,
       82, 14, 82, 33, 47, 64,  1, 49, 28, 50, 40, 93, 66, 57, 33, 48, 13,
       43, 94, 95, 49, 59, 24, 81, 91, 91, 95, 79, 31,  7,  9, 31, 86, 15,
       69, 25,  5, 53, 80, 37, 72, 48, 42, 93, 72, 52, 97,  4, 21, 12, 44,
       85, 39, 42,  4, 66, 63,  9, 94,  6, 91,  4, 48, 96, 17, 88, 66, 95,
       37, 54, 30, 20, 18, 96,  8, 29, 19, 24, 58, 59,  1, 99, 47,  1, 66,
        9,  7, 42, 33, 31

In [54]:
# length of the array created
len(int_dialect_score)

500

In [55]:
# min value is inclusive and max value is exclusive
print(min(int_dialect_score))
print(max(int_dialect_score)) #Python int
max(int_dialect_score) #NumPy int


1
99


np.int64(99)

In [56]:
max(int_dialect_score).item()

99

In [57]:
# adding new column to the dataframe using Array
df_exams['Dialect_Score'] = int_dialect_score
df_exams

,Student_ID,Gender,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result,Language_Score,Language_score,Dialect_Score
0,1,Male,21,14,93,93,1,71,74,Pass,70,0,51
1,2,Female,21,21,94,69,1,95,79,Pass,70,1,91
2,3,Male,17,24,83,73,8,50,53,Pass,70,2,86
3,4,Male,19,28,52,99,4,59,74,Fail,70,3,49
4,5,Male,18,9,86,98,1,63,87,Pass,70,4,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,Male,21,21,73,83,0,40,77,Pass,70,495,92
496,497,Male,21,18,69,63,10,96,55,Pass,70,496,43
497,498,Female,20,35,86,85,6,68,41,Fail,70,497,56
498,499,Male,18,28,53,82,5,84,79,Fail,70,498,50


In [58]:
# create random float numbers from 1 to 100
np.random.uniform(1,100,size=500)

array([ 1.19623305, 20.74604042, 56.82560969, 84.4464973 , 79.32138862,
       36.9410094 , 93.9838664 ,  4.68298362, 83.45308514, 21.12658985,
       74.2201546 , 76.46069295, 98.79543134, 38.31356185, 85.2941366 ,
       76.50801116, 83.90252956, 48.19138964, 36.17087601, 33.83771998,
       74.98873292, 47.69102836, 67.90832553, 81.85645103,  8.95994353,
       58.08388685, 81.92332611,  6.92518152, 83.47657037, 53.10676573,
       24.45587132, 90.60191604, 40.97726301, 13.4969852 , 32.52081525,
       90.88864673, 36.02420954, 87.03792536, 98.65406765, 42.6520068 ,
       69.93775564, 85.37763054, 88.355934  , 25.98632792, 62.27760263,
       63.63373674, 85.22115735, 69.93885072, 59.92346703, 77.25630656,
       43.01610282, 96.72503271, 55.93977702, 86.69164759, 64.0635555 ,
       73.21283105, 84.20073731, 38.56922419, 22.81728647, 80.80047097,
       51.0346827 , 55.66445038, 46.5310483 , 56.29218251, 54.97388073,
       34.57761086,  3.9481966 , 71.19793671, 31.35250693, 22.15

### 1.3 using assign() method

In [67]:
# create random numbers for new score column
score1 = np.random.randint(1,100, size = 500)
score2 = np.random.randint(1,100, size = 500)

In [70]:
# create series using random integers
series1 = pd.Series(score1, index=np.arange(0,500,1))
series2 = pd.Series(score2, index=np.arange(0,500,1))

In [84]:
# using assign() method to add multiple columns
df_exams = df_exams.assign(Score_1 = series1, Score_2 = series2)
# assign() creates copy of the dataframe, to update we need to overwrite the dataframe which is done in the above statemtent

In [85]:
# show dataframe
df_exams

,Student_ID,Gender,Age,Test,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result,Language_Score,Language_score,Dialect_Score,Score_1,Score_2
0,1,Male,21,20,14,93,93,1,71,74,Pass,70,0,51,20,21
1,2,Female,21,99,21,94,69,1,95,79,Pass,70,1,91,99,86
2,3,Male,17,80,24,83,73,8,50,53,Pass,70,2,86,80,15
3,4,Male,19,18,28,52,99,4,59,74,Fail,70,3,49,18,59
4,5,Male,18,40,9,86,98,1,63,87,Pass,70,4,65,40,77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,Male,21,67,21,73,83,0,40,77,Pass,70,495,92,67,92
496,497,Male,21,83,18,69,63,10,96,55,Pass,70,496,43,83,50
497,498,Female,20,26,35,86,85,6,68,41,Fail,70,497,56,26,23
498,499,Male,18,35,28,53,82,5,84,79,Fail,70,498,50,35,50


### using insert() method


In [83]:
# using index() method to add column in specific location
# index() doesn't create copy, it updates the values (not like assign())
df_exams.insert(3, 'Test', series1)

ValueError: cannot insert Test, already exists

In [86]:
#show dataframe
df_exams

,Student_ID,Gender,Age,Test,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result,Language_Score,Language_score,Dialect_Score,Score_1,Score_2
0,1,Male,21,20,14,93,93,1,71,74,Pass,70,0,51,20,21
1,2,Female,21,99,21,94,69,1,95,79,Pass,70,1,91,99,86
2,3,Male,17,80,24,83,73,8,50,53,Pass,70,2,86,80,15
3,4,Male,19,18,28,52,99,4,59,74,Fail,70,3,49,18,59
4,5,Male,18,40,9,86,98,1,63,87,Pass,70,4,65,40,77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,Male,21,67,21,73,83,0,40,77,Pass,70,495,92,67,92
496,497,Male,21,83,18,69,63,10,96,55,Pass,70,496,43,83,50
497,498,Female,20,26,35,86,85,6,68,41,Fail,70,497,56,26,23
498,499,Male,18,35,28,53,82,5,84,79,Fail,70,498,50,35,50
